guests = ['Martha','Mercy','William','Millenium']
print('Hello '+guests[0]+','+'Welcome to dinner')
print('Hello '+guests[1]+','+'Welcome to dinner')
print('Hello '+guests[2]+','+'Welcome to dinner')
print('Hello '+guests[3]+','+'Welcome to dinner')
guest_who_not_attend = guests.pop(1)
print(guest_who_not_attend)
guests.append('Joseph')
print('Hello '+guests[0]+','+'Welcome to dinner')
print('Hello '+guests[1]+','+'Welcome to dinner')
print('Hello '+guests[2]+','+'Welcome to dinner')
print('Hello '+guests[3]+','+'Welcome to dinner')

print('############# BIGGER TABLE DINNER ##########')
guests.insert(0,'Juma')
guests.insert(2,'Omary')
guests.append('Zulfa')
print('Hello '+guests[0]+','+'Welcome to dinner')
print('Hello '+guests[1]+','+'Welcome to dinner')
print('Hello '+guests[2]+','+'Welcome to dinner')
print('Hello '+guests[3]+','+'Welcome to dinner')
print('Hello '+guests[4]+','+'Welcome to dinner')
print('Hello '+guests[5]+','+'Welcome to dinner')
print('Hello '+guests[6]+','+'Welcome to dinner')
